name: ardac-toolbox
channels:
  - defaults
  - conda-forge
dependencies:
  - affine=2.3.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - anyio=4.2.0
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.3
  - blas=2.123
  - blas-devel=3.9.0
  - bleach=4.1.0
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.7.2
  - cairo=1.16.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - cfitsio=3.470
  - cftime=1.6.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - expat=2.6.2
  - fiona=1.9.5
  - folium=0.14.0
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - frozenlist=1.4.0
  - gdal=3.6.2
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - h5netcdf=1.2.0
  - h5py=3.11.0
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - ipykernel=6.28.0
  - ipython=8.25.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.11
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - kealib=1.5.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.7.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgdal=3.6.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libopenblas=0.3.27
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libzip=1.8.0
  - llvm-openmp=18.1.8
  - lz4-c=1.9.4
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.6
  - minizip=4.0.3
  - mistune=2.0.4
  - multidict=6.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - netcdf4=1.6.2
  - networkx=3.3
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openblas=0.3.27
  - openjpeg=2.4.0
  - openssl=3.0.14
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.40.0
  - platformdirs=3.10.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=9.3.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=5
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qhull=2020.2
  - rasterio=1.3.10
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rioxarray=0.17.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - send2trash=1.8.2
  - setuptools=69.5.1
  - shapely=2.0.1
  - six=1.16.0
  - sniffio=1.3.0
  - snuggs=1.4.7
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tiledb=2.3.3
  - tinycss2=1.2.1
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.2.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - xarray=2023.6.0
  - xerces-c=3.2.4
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
